const defaultProducts=[
{id:1,name:"Glucomètre YASEE",cat:"Diagnostic",desc:"Kit complet : appareil, 50 bandelettes, 50 lancettes et autopiqueur.",price:"12 000 FCFA",partnerPrice:"",status:"Disponible",image:""},
{id:2,name:"Glucomètre SINOCARE",cat:"Diagnostic",desc:"Kit complet pour le suivi de la glycémie.",price:"12 000 FCFA",partnerPrice:"",status:"Disponible",image:""},
{id:3,name:"Bandelettes SINOCARE",cat:"Consommables",desc:"Boîte de 50 bandelettes.",price:"8 000 FCFA",partnerPrice:"",status:"Disponible",image:""},
{id:4,name:"Tensiomètre électronique rechargeable",cat:"Diagnostic",desc:"Appareil de mesure de la pression artérielle.",price:"Sur demande",partnerPrice:"",status:"Disponible",image:""},
{id:5,name:"Tubes EDTA",cat:"Laboratoire",desc:"Consommables de prélèvement pour analyses.",price:"Sur demande",partnerPrice:"",status:"Disponible",image:""},
{id:6,name:"Gants médicaux",cat:"Consommables",desc:"Gants à usage médical, différentes tailles.",price:"Sur demande",partnerPrice:"",status:"Disponible",image:""},
{id:7,name:"Microscope",cat:"Laboratoire",desc:"Équipement de laboratoire selon configuration.",price:"Sur demande",partnerPrice:"",status:"Bientôt disponible",image:""},
{id:8,name:"Réactifs de laboratoire",cat:"Réactifs",desc:"Références selon vos analyses et besoins.",price:"Sur demande",partnerPrice:"",status:"Bientôt disponible",image:""}
];
const defaultPartners=[];
let products=JSON.parse(localStorage.getItem("biomed_products")||"null")||defaultProducts;
let partners=JSON.parse(localStorage.getItem("biomed_partners")||"null")||defaultPartners;
let category="Tous";

function escapeHtml(s){return String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function renderBrand(){const logo=localStorage.getItem("biomed_logo")||"";document.querySelectorAll(".site-logo-img").forEach(el=>{el.src=logo;el.style.display=logo?"block":"none"});document.querySelectorAll(".site-logo-text").forEach(el=>el.style.display=logo?"none":"inline");}
function renderPartners(){const box=document.getElementById("partnersList");if(!box)return;const partnersHtml=partners.length?partners.map(p=>`<div class="info-card partner-card">${p.logo?`<img src="${p.logo}" alt="Logo ${escapeHtml(p.name)}" class="partner-logo">`:""}<h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description||"")}</p>${p.contact?`<p>📞 ${escapeHtml(p.contact)}</p>`:""}</div>`).join(""):"<div class=\"info-card\"><h3>Nos partenaires</h3><p>Votre logo peut apparaître ici. Contactez BIOMED-TOGO pour rejoindre notre réseau.</p></div>";box.innerHTML=partnersHtml;const rows=document.getElementById("partnerPriceRows");if(rows)rows.innerHTML=products.map(p=>`<tr><td>${escapeHtml(p.name)}</td><td>${escapeHtml(p.price||"Sur demande")}</td><td><strong>${escapeHtml(p.partnerPrice||"Sur demande")}</strong></td></tr>`).join("");}
function partnerLogin(){const u=(document.getElementById("partnerUser")?.value||"").trim();const pw=document.getElementById("partnerPass")?.value||"";const accounts=JSON.parse(localStorage.getItem("biomed_partner_accounts")||"[]");const found=accounts.find(a=>a.username===u&&a.password===pw);if(found){sessionStorage.setItem("biomed_partner_logged","1");document.getElementById("partnerLogin").style.display="none";document.getElementById("partnerArea").style.display="block";renderPartners();}else{document.getElementById("partnerMsg").textContent="Identifiant ou mot de passe incorrect.";}}
function partnerLogout(){sessionStorage.removeItem("biomed_partner_logged");document.getElementById("partnerArea").style.display="none";document.getElementById("partnerLogin").style.display="block";document.getElementById("partnerPass").value="";}
function initPartnerAccess(){if(sessionStorage.getItem("biomed_partner_logged")==="1"){document.getElementById("partnerLogin").style.display="none";document.getElementById("partnerArea").style.display="block";renderPartners();}}

function renderFilters(){let cats=["Tous",...new Set(products.map(p=>p.cat))];document.getElementById("filters").innerHTML=cats.map(c=>`<button class="filter ${c===category?"active":""}" onclick="category='${String(c).replace(/'/g,"\\'")}';renderFilters();renderProducts()">${escapeHtml(c)}</button>`).join("")}
function renderProducts(){let q=(document.getElementById("search")?.value||"").toLowerCase();let list=products.filter(p=>(category==="Tous"||p.cat===category)&&(p.name+" "+p.desc).toLowerCase().includes(q));document.getElementById("products").innerHTML=list.length?list.map(p=>`<article class="product">${p.image?`<img class="product-image" src="${p.image}" alt="${escapeHtml(p.name)}">`:`<div class="icon">${p.cat==="Diagnostic"?"🩺":p.cat==="Laboratoire"?"🔬":p.cat==="Réactifs"?"🧪":"📦"}</div>`}<h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.desc)}</p><div class="price">${escapeHtml(p.price)}</div><span class="status ${p.status.includes("Bientôt")?"soon":""}">${escapeHtml(p.status)}</span><button class="btn primary" style="margin-top:14px" onclick="orderProduct('${String(p.name).replace(/'/g,"\\'")}')">Commander</button></article>`).join(""):"<p>Aucun produit trouvé.</p>"}
function orderProduct(name){document.getElementById("items").value=name+" — Quantité : ";location.hash="commande";document.getElementById("name").focus()}
document.getElementById("orderForm")?.addEventListener("submit",e=>{e.preventDefault();let n=document.getElementById("name").value,p=document.getElementById("phone").value,i=document.getElementById("items").value;let msg=`Bonjour BIOMED-TOGO,%0A%0AJe souhaite passer une commande.%0A%0ANom/Structure : ${encodeURIComponent(n)}%0ATéléphone : ${encodeURIComponent(p)}%0ABesoin : ${encodeURIComponent(i)}%0A%0AMerci.`;window.open("https://wa.me/22897571303?text="+msg,"_blank")});
renderBrand();renderFilters();renderProducts();initPartnerAccess();
